# Generated by Django 5.2 on 2025-05-03 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(254)]),
        ),
    ]
